#! /bin/sh

set -uf

# There's probably a better way of doing this?
# But since the install script puts the files in /usr/share, just
# hard-coding the path for now
SCRIPT_PATH=/usr/share/lvm-autosnap

# shellcheck source=cli.sh
. "$SCRIPT_PATH/cli.sh"

cli_main "$@"
