#!/bin/sh
sed -i -z -r 's#sha256sums=\([^)]+\)##' PKGBUILD.dev
sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' PKGBUILD.dev # remove trailing newlines
printf "\n%s\n\n" "$(makepkg -g -p PKGBUILD.dev)" >> PKGBUILD.dev
git add PKGBUILD.dev
